from typing import Protocol


class Repository(Protocol):
    async def create(self, *ag, **kw): ...
    async def get(self, **kw): ...
    async def update(self, *ag, **kw): ...
    async def delete(self, *ag, **kw): ...
    async def get_by_id(self, id): ...
    async def delete_where(self, **kw): ...
    async def search(self, skip=0, limit=100, **kw): ...
