from typing import Protocol
from .models import Base


class Repository(Protocol):
    async def create(self, *ag, **kw) -> Base: ...
    async def get(self, **kw) -> Base | None: ...
    async def get_many(self,) -> list[Base]: ...
    async def update(self, obj: Base, *ag, **kw) -> Base: ...
    async def delete(self, obj: Base, *ag, **kw) -> None: ...
    async def get_by_id(self, id) -> Base | None: ...
    async def delete_where(self, **kw) -> None: ...
    async def search(self, skip=0, limit=100, **kw) -> list[Base]: ...
