from typing import Protocol


class Repository(Protocol):
    async def create(self, *ag, **kw): ...
    async def get(self, **kw): ...
    async def update(self, *ag, **kw): ...
    async def delete(self, *ag, **kw): ...
